apiVersion: v1
kind: Pod
metadata:
  name: volpod
  namespace: qa
spec:
  containers:
    - name: volapp
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
      volumeMounts:
        - mountPath: "/data"
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: mypvc
