apiVersion: v1
kind: Pod
metadata:
  name: hostvol
  namespace: qa
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo Hello from Pod > /host-data/file.txt && sleep 3600"]
    volumeMounts:
    - name: host-vol
      mountPath: /host-data
  - name: app2
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: host-vol
      mountPath: /host-data
  volumes:
    - name: host-vol
      hostPath:
       path: /data/app
       type: DirectoryOrCreate
