apiVersion: v1
kind: pod
metadata:
  name: pod-vol
  namespace: qa
spec:
  containers:
  - name: container1
    image: busybox
    volumeMounts:
    - mountPath: /cache
      name: myvol
  volumes:
    - name: myvol
      emptyDir: {}
    

