apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  namespace: qa
spec:
  containers:
  - name: write
    image: busybox
    command: ["sh", "-c", "touch  /cache/file.txt && sleep 3600"]
    volumeMounts:
    - name: myvol
      mountPath: /cache

  - name: read
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: myvol
      mountPath: /cache

  volumes:
  - name: myvol
    emptyDir: {}
